### PR TITLE
Fix JSON meta data of production country ISO code

### LINKED ISSUE #14: [BUG] Wrong JSON Metadata for Iso3166_1 of ProductionCountries
**Describe the bug**
JSON Metadata for Iso3166_1 is `json:"iso_31661_1"` right now, it should be `json:"iso_3166_1"` instead as documented here: https://developers.themoviedb.org/3/movies/get-movie-details

**To Reproduce**
Call GetMovieDetails for any movie and checkout MovieDetails.ProductionCountries[0].Iso3166_1

### PR DESCRIPTION
**Pull request by cevatbarisyilmaz**
# Description

Fixes the typo in json metada of Iso3166_1 for ProductionCountries in MovieDetails

Fixes #14 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Yes

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cyruzin** [comment]
Could you check why Travis CI is failing?

**Comment by cevatbarisyilmaz** [comment]
It seems it was failing with the current last commit as well https://travis-ci.org/cyruzin/golang-tmdb/jobs/652561436?utm_medium=notification&utm_source=github_status So I don't think it's about contents of this this pull request.

**Comment by cyruzin** [comment]
> It seems it was failing with the current last commit as well https://travis-ci.org/cyruzin/golang-tmdb/jobs/652561436?utm_medium=notification&utm_source=github_status So I don't think it's about contents of this this pull request.

I'll investigate this issue and as soon as fix it I'll merge your pull.

**Comment by cyruzin** [comment]
@cevatbarisyilmaz done.

**Pull request merged**
